apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kstream-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: kstream
  template: 
    metadata: 
      labels: 
        app: kstream
    spec: 
      containers: 
        - 
          # args: 
            
          command: 
            - java
            - '-Dpair=BTCUSDT'
            - '-cp'
            - 'kafkaStreams.jar'
            - '-Dthread={ "class": "TradeStreamProducer", "params": {"bootstrapServers": "b-1.kafkadevapp.ggeixg.c2.kafka.ap-northeast-1.amazonaws.com:9094", "pair": "BTCUSDT" } }'
            - 'com.tradingbot.kafka.RunTest'
          image: "126880002495.dkr.ecr.ap-northeast-1.amazonaws.com/test-ecr:00ef247"
          name: kstream
          resources:
            requests:
              memory: "4096Mi"
              cpu: "1000m"
            limits:
              memory: "4096Mi"
              cpu: "1000m"
